<?php return array (
  'Revenue' => 'Inkomst',
  'Employees' => 'anställda',
  'Parent' => 'Förälder',
  'Primary Contact' => 'Primärkontakt',
  'Symbol' => 'Symbol',
  'Share {opportunity}' => 'Dela {opportunity}',
  '{module} Report' => '{Modul} rapport',
  'Year Established' => 'Grundades år',
  '{account}' => '{konto}',
  'Campaign Form' => 'Kampanjformulär',
  'This form will allow you to generate a campaign to mail related {contacts} of the {accounts} displayed in the report below. Select "Primary {contacts}" to only email {contacts} which are set as the Primary {contact} for an {account}. Select "All" to email all related {contacts} on each {account}.' => 'I det här formuläret kan du generera en kampanj till mailrelaterade {contacts} av {accounts} som visas i rapporten nedan. Välj "Primär {kontakter}" till bara e-post {contacts} som är inställda som Primär {contact} för ett {konto}. Välj "Alla" för att skicka e-post till alla relaterade {contacts} på varje {account}.',
  'Primary {module}' => 'Primär {modul}',
  'Bug Report Attributes' => 'Felrapport attribut',
  'Account Record' => 'Kontoinspelning',
);
