<?php return array (
  'Create New Module' => 'Skapa ny modul',
  'Module Title' => 'Modul Titel',
  'The name for your new module' => 'Namnet på din nya modul',
  '(Optional) What to call individual records, e.g. "Create new X"' => '(Valfritt) Vad ska man ringa enskilda poster, t.ex. "Skapa ny X"',
  'DB Table Name' => 'DB-tabellnamn',
  'Optional (alphanumeric only, must start with a letter)' => 'Valfritt (endast alfanumerisk, måste börja med ett brev)',
  '{X} List' => '{X} Lista',
  'Create {X}' => 'Skapa {X}',
  'Import {X}' => 'Importera {X}',
  'Export {X}' => 'Exportera {X}',
  'Create New {X}' => 'Skapa ny {X}',
  'Edit {X}' => 'Redigera {X}',
  'Delete {X}' => 'Ta bort {X}',
  'View {X}' => 'Visa {X}',
  '{modelName} Attributes' => '{modelName} Attribut',
  'Update {X}' => 'Uppdatera {X}',
  'Unable to create table for custom module.' => 'Det gick inte att skapa tabell för anpassad modul.',
  'Manage {X}' => 'Hantera {X}',
  'Invalid table name' => 'Ogiltigt tabellnamn',
  'A module with that name already exists' => 'En modul med det namnet finns redan',
  'Unable to create custom module directory.' => 'Det gick inte att skapa en anpassad modulkatalog.',
  'Unable to create config file for custom module.' => 'Det gick inte att skapa konfigurationsfil för anpassad modul.',
);
