<?php return array (
  '{poster} posted a new reply to {topic}.' => '{poster} skickade ett nytt svar till {topic}.',
  '{poster} posted a new reply to a topic, but that reply has been deleted.' => '{poster} postade ett nytt svar på ett ämne, men det svaret har tagits bort.',
  'Topic Title' => 'Ämnestitel',
  'Replies' => 'svar',
  'Latest Post' => 'Senaste posten',
  'Create {topic}' => 'Skapa {ämne}',
  'Are you sure you want to delete this post?' => 'Är du säker på att du vill radera det här inlägget?',
  'Posted {datetime}.' => 'Inlagd {datetime}.',
  'Edited by {user} - {datetime}.' => 'Redigerad av {user} - {datetime}.',
  'Update Reply to {topic}' => 'Uppdatera Svara på {topic}',
  'New Reply' => 'Nytt svar',
  'Unpin Topic' => 'Unpin Topic',
  'Pin Topic' => 'Pin-ämne',
  '{topics} List' => '{ämnen} Lista',
  'View {topic}' => 'Visa {ämne}',
  'Edit {topic}' => 'Redigera {ämne}',
  'Sorting' => 'Sortering',
  'Most Recent' => 'Senaste',
  'Alphabetical' => 'Alfabetisk',
  'Most Popular' => 'Mest populär',
  '{poster}posted a new reply to {topic}.' => '{Poster} skickade ett nytt svar till {topic}.',
  '{poster}posted a new reply to a topic, but that reply has been deleted.' => '{poster} postade ett nytt svar på ett ämne, men det svaret har tagits bort.',
);
