<?php return array (
  '{leads} List' => '{Leads} List',
  'Create {lead}' => 'Skapa {lead}',
  'Edit {lead}' => 'Redigera {lead}',
  'Delete {lead}' => 'Ta bort {lead}',
  'Convert to {contact}' => 'Konvertera till {contact}',
  'Convert to {opportunity}' => 'Konvertera till {opportunity}',
  'Import {leads}' => 'Importera {leads}',
  'Export {leads}' => 'Exportera {leads}',
  'Conversion Date' => 'Konverteringsdatum',
  'Converted' => 'Konverterad',
  'Converted To' => 'Konverterat till',
  'View Lead' => 'Visa bly',
  'Leads:' => 'leder:',
  'Lead' => 'Leda',
  'This record has been converted. To view the new record, click {here}.' => 'Denna post har konverterats. För att se den nya posten klickar du på {här}.',
  'Edit Lead' => 'Redigera bly',
);
